<?php


class CategoryCustom extends Category
{
    public function attributeLabels()
    {
        return array(
            'name'=>'Nama',
            'description'=>'Keterangan',
            'created_by' => 'Dibuat Oleh',
            'created_at' => 'Dibuat Pada',
            'updated_by' => 'Diperbarui Oleh',
            'updated_at' => 'Terakhir diperbarui'
        );
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}