<?php
/**
 * Class CityCustom
 */

class CityCustom extends RefCities
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'id'=>'Kode Wialayah',
            'name'=> 'Nama',
            'state_id' => 'Provinsi'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllOptions() {
        $criteria = new CDbCriteria();
        $criteria->order = 'name';

        $model = self::model()->findAll($criteria);
        $options = array();
        foreach ($model as $row) {
            $options[$row->id] = $row->name;
        }
        return $options;
    }

    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'state' => array(self::BELONGS_TO, 'StateCustom', 'state_id'),
            'districts' => array(self::HAS_MANY, 'DistrictCustom', 'city_id'),
        );
    }
}