<?php
/**
 * Class CityCustom
 */

class CityCustom extends RefCities
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'id' => 'Kode Wilayah',
            'name' => 'Nama',
            'state_id' => 'Provinsi',
            'unit_code' => 'Kode Prisma'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllOptions()
    {
        $criteria = new CDbCriteria();
        $criteria->order = 'name';

        $model = self::model()->findAll($criteria);
        $options = array();
        foreach ($model as $row) {
            $options[$row->id] = $row->name;
        }
        return $options;
    }

    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'state' => array(self::BELONGS_TO, 'StateCustom', 'state_id'),
            'districts' => array(self::HAS_MANY, 'DistrictCustom', 'city_id'),
        );
    }

    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('state_id', $this->state_id, true);
        $criteria->compare('name', strtoupper($this->name), true);
        $criteria->compare('unit_code', $this->unit_code, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}