<?php
/**
 * Class DistrictCustom
 */

class DistrictCustom extends RefDistricts
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'id'=>'Kode Wilayah',
            'name' => 'Nama',
            'city_id' => 'Kab. / Kota'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllOptions() {
        $criteria = new CDbCriteria();
        $criteria->order = 'name';

        $model = self::model()->findAll($criteria);
        $options = array();
        foreach ($model as $row) {
            $options[$row->id] = $row->name;
        }
        return $options;
    }

    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'city' => array(self::BELONGS_TO, 'CityCustom', 'city_id'),
        );
    }

    /**
     * @return CActiveDataProvider
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id,true);
        $criteria->compare('city_id',$this->city_id,true);
        $criteria->compare('name',strtoupper($this->name),true);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
        ));
    }
}