<?php

class EventCustom extends event {

    public function attributeLabels()
    {
        return array(
            'title' => 'Judul Event',
            'start_time' => 'Waktu Mulai',
            'end_time' => 'Waktu Berakhir',
            'banner_url' => 'Banner',
            'description' => 'Keterangan'
        );
    }

    public function rules()
    {
        return parent::rules();
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}