<?php
/**
 * Class NewsCustom
 */

class NewsCustom extends News
{
    const FLAG_PUBLISHED_INACTIVE = 0;
    const FLAG_PUBLISHED_ACTIVE = 1;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'title' => 'Judul',
            'flag_published' => 'Status Publikasi',
            'cat_id' => 'Kategori'
        );
    }

    /**
     * @param string $className
     * @return NewsCustom
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function scopes()
    {
        return array(
            'detail'=>array(
                'select'=>"id, title, content, permalink, banner, flag_published, to_char(created_at,'DD Month YYYY, HH24:MI:SS') AS created_at, created_by" ,
            ),
            'latest'=>array(
                'order'=>'timestamp_created DESC'
            ),
        );
    }

    /**
     * Find page by permalink
     */
    public function findByPermalink($permalink)
    {
        return self::model()->detail()->findByAttributes(array(
            'permalink'=>$permalink,
            'flag_published'=>self::FLAG_PUBLISHED_ACTIVE
        ));
    }
}