<?php
/**
 * Class NewsCustom
 */

class NewsCustom extends News
{
    const FLAG_PUBLISHED_INACTIVE = 0;
    const FLAG_PUBLISHED_ACTIVE = 1;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'title' => 'Judul',
            'flag_published' => 'Status Publikasi',
            'cat_id' => 'Kategori'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}