<?php


class StateCustom extends RefStates
{
    public function attributeLabels()
    {
        return array(
            'id' => 'Kode Wilayah',
            'name' => 'Nama'
        );
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllOptions()
    {
        $criteria = new CDbCriteria();
        $criteria->order = 'name';
        $model = self::model()->findAll($criteria);
        $options = array();
        foreach ($model as $row) {
            $options[$row->id] = $row->name;
        }
        return $options;
    }

    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', strtoupper($this->name), true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}