<?php


class StateCustom extends RefStates
{
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllOptions() {
        $criteria = new CDbCriteria();
        $criteria->order = 'name';
        $model = self::model()->findAll($criteria);
        $options = array();
        foreach ($model as $row) {
            $options[$row->id] = $row->name;
        }
        return $options;
    }
}