<?php

/**
 * Class UnitCustom
 * * The followings are the available model relations:
 * @property AddressCustom $address
 */

class UnitCustom extends Unit
{

    public function attributeLabels()
    {
        return array(
            'unit_no' => 'Nomor Unit',
            'owner' => 'Pemilik',
            'address_id' => 'Alamat',
            'wa_number' => 'Nomor WA',
            'trainer' => 'Pelatih',
            'consultant' => 'Konsultan',
            'status' => 'Status',
            'start_date' => 'Mulai Aktif',
            'expired_at' => 'Berakhir Lisensi'
        );
    }

    public function rules()
    {
        $parent = parent::rules();
        return array_merge($parent,
            array()
        );
    }

    /**
     * @param string $className
     * @return UnitCustom
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function search()
    {
        return parent::search(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'address' => array(self::BELONGS_TO, 'AddressCustom', 'address_id'),
        );
    }

    public function getStatus()
    {
        return UnitStatus::getStatus($this->status);
    }

    /**
     * @return array
     */
    public static function getAllOptions() {
        $criteria = new CDbCriteria();
        $criteria->order = 'unit_no ASC';
        $models = self::model()->findAll($criteria);
        $options = array();
        if (!empty($models)) {
            foreach ($models as $row) {
                $options[$row->id] = $row->unit_no.' ('.$row->address->getCity().'/'.$row->address->getDistrict().') - '.$row->owner;
            }
        }
        return $options;
    }
}